In [43]:
import os
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer
import pandas as pd
import numpy as np
import pyspark.pandas as ps
from pyspark.sql import SparkSession
from pyspark.ml.feature import Tokenizer
from pyspark.ml.feature import CountVectorizer
from pyspark.ml.feature import IDF
from pyspark.ml.feature import StringIndexer
from pyspark.ml.feature import VectorAssembler
from pyspark.sql.functions import col
from pyspark.sql import SQLContext
from pyspark.ml.feature import Word2Vec
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from gensim.models import Word2Vec

from nltk.tokenize import word_tokenize
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from pyspark.sql import SparkSession
from pyspark.ml.feature import Tokenizer, Word2Vec, StringIndexer, IndexToString, StopWordsRemover
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import MulticlassClassificationEvaluator,BinaryClassificationEvaluator
from pyspark.ml.tuning import ParamGridBuilder, TrainValidationSplit
from gensim.models import Word2Vec
import numpy as np
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from pyspark.ml import Pipeline
from pyspark.ml.feature import Tokenizer, StopWordsRemover, Word2Vec
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.feature import StringIndexer, IndexToString
from pyspark.ml.evaluation import MulticlassClassificationEvaluator


In [44]:
os.getcwd()
os.chdir('/home/hadi/Datasets')

Without Distributed Computing/Without PySpark


In [45]:
df_undistributed=pd.read_csv('IMDB Dataset.csv')
df_undsitributed_train=df_undistributed.iloc[:40000,:]
df_undsitributed_test=df_undistributed.iloc[10000:,:]


words=[',','<','>','?','br','/','.','-',';',':','(',')','[',']','{','}','!','@','#','$','%','^','&','*','_','+','=','|','\\','"',"'",'<br,','<br','<br>','<br/>','<br />','<br >','<br /']
lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words('english'))
stop_words.add('.')
stop_words.add('<')
stop_words.add('>')
stop_words.add('?')
stop_words.add('br')
stop_words.add('/')
stop_words.add('.')
stop_words.add('-')
stop_words.add(';')

for i in range(len(df_undistributed['review'])):
	word_tokens = word_tokenize(df_undistributed['review'][i])
	filtered_sentence = [w for w in word_tokens if not w in stop_words and w != ',']
	filtered_sentence = []
	for w in word_tokens:
		if w not in stop_words and w != ',':
			lemmatizer.lemmatize(w)
			filtered_sentence.append(w)
	df_undistributed['review'][i] = ' '.join(filtered_sentence)
	df_undistributed['review'][i] = df_undistributed['review'][i].lower()


tokenized_reviews = [word_tokenize(review) for review in df_undistributed['review']]







/tmp/ipykernel_29981/2999134276.py:28: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_undistributed['review'][i] = ' '.join(filtered_sentence)
/tmp/ipykernel_29981/2999134276.py:29: FutureWarning: ChainedAssignmentError: behaviour will cha

In [46]:
from gensim.models import Word2Vec
import numpy as np
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score

# Train Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_reviews, vector_size=30, window=5, min_count=1, workers=4)

def document_vector(word2vec_model, doc):
    doc = [word for word in doc if word in word2vec_model.wv.key_to_index]
    if len(doc) == 0:
        return np.zeros(word2vec_model.vector_size)
    return np.mean(word2vec_model.wv[doc], axis=0)  

X = [document_vector(word2vec_model, doc) for doc in tokenized_reviews]
y = df_undistributed['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train RandomForestClassifier
RF = RandomForestClassifier(max_depth=4)
RF.fit(X_train, y_train)

# Predict and Evaluate
y_pred = RF.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('F1:', f1_score(y_test, y_pred, average='weighted'))

# Test with sample text
text = 'I love this movie, But the title is not good overall the movie was lovely'
text = word_tokenize(text)
text = [document_vector(word2vec_model, text)]
print(RF.predict(text))
print(RF.predict_proba(text))

text_2 = 'I hate this movie'
text_2 = word_tokenize(text_2)
text_2 = [document_vector(word2vec_model, text_2)]
print(RF.predict(text_2))
print(RF.predict_proba(text_2))

text_3 = 'The movie was very strong and powerful'
text_3 = word_tokenize(text_3)
text_3 = [document_vector(word2vec_model, text_3)]
print(RF.predict(text_3))
print(RF.predict_proba(text_3))


Accuracy: 0.7534
F1: 0.7533951661757595
['positive']
[[0.43786767 0.56213233]]
['positive']
[[0.451275 0.548725]]
['positive']
[[0.3066833 0.6933167]]


DISTRIBUTED WORD EMBEDDINGS

In [47]:
spark=SparkSession.builder \
    .appName("Spark NLP") \
    .master("spark://172.28.111.195:7077") \
    .config("spark.driver.memory", "16G") \
    .config("spark.serializer", "org.apache.spark.serializer.KryoSerializer") \
    .config("spark.kryoserializer.buffer.max", "2000M") \
    .config("spark.driver.maxResultSize", "0") \
    .config("spark.jars.packages", "com.johnsnowlabs.nlp:spark-nlp_2.12:5.3.3") \
    .getOrCreate()


In [48]:
df=pd.read_csv('IMDB Dataset.csv')
df.head()
df_train=df[:20000]
df_test=df[20000:]
spark_df=spark.createDataFrame(df)
spark_df_train,spark_df_test=spark_df.randomSplit([0.8,0.2],seed=42)

In [52]:
from pyspark.ml import Pipeline
from pyspark.ml.feature import Tokenizer, StopWordsRemover, Word2Vec
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.feature import StringIndexer, IndexToString
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

# Define stopwords and tokenizer
words = [',', '<', '>', '?', 'br', '/', '.', '-', ';', ':', '(', ')', '[', ']', '{', '}', '!', '@', '#', '$', '%', '^', '&', '*', '_', '+', '=', '|', '\\', '"', "'", '<br,', '<br', '<br>', '<br/>', '<br />', '<br >', '<br /']
tokenizer = Tokenizer(inputCol="review", outputCol="words")

# Define remover for stopwords
remover = StopWordsRemover(inputCol="words", outputCol="filtered", stopWords=words)

# Define Word2Vec model
word2vec = Word2Vec(vectorSize=30, minCount=1, windowSize=5, inputCol=remover.getOutputCol(), outputCol="features")

# Define label indexer
labelIndexer = StringIndexer(inputCol="sentiment", outputCol="label").fit(spark_df_train)

# Define Random Forest classifier
rf = RandomForestClassifier(numTrees=100, maxDepth=4, labelCol="label", featuresCol="features")

# Define label converter
labelConverter = IndexToString(inputCol="prediction", outputCol="predicted_sentiment", labels=labelIndexer.labels)

# Define pipeline
pipeline = Pipeline(stages=[tokenizer, remover, word2vec, labelIndexer, rf, labelConverter])

# Train the pipeline
model = pipeline.fit(spark_df_train)

# Make predictions
prediction = model.transform(spark_df_test)

# Evaluate the model
evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
accuracy = evaluator.evaluate(prediction)
print("Accuracy:", accuracy)

# Test with sample text
text_spark = 'I love this movie, But the title is not good overall the movie was lovely'
text_spark_2 = 'I hate this movie'
text_spark_3 = 'The movie was very strong and powerful'

text_data = [text_spark, text_spark_2, text_spark_3]
text_data = pd.DataFrame(text_data, columns=['review'])
text_data = spark.createDataFrame(text_data)

prediction = model.transform(text_data)
prediction.show()


24/05/01 22:07:44 WARN TaskSetManager: Stage 78 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:07:46 WARN TaskSetManager: Stage 81 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:08:00 WARN TaskSetManager: Stage 83 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:09:42 WARN TaskSetManager: Stage 86 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:09:46 WARN TaskSetManager: Stage 87 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:09:51 WARN TaskSetManager: Stage 88 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/01 22:09:55 WARN TaskSetManager: Stage 90 contains a task of very large size (8079 KiB). The maximum recommended task size is 1000 KiB.
24/05/

Accuracy: 0.6688687874784023


24/05/01 22:10:16 WARN StringIndexerModel: Input column sentiment does not exist during transformation. Skip StringIndexerModel for this column.


+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+-------------------+
|              review|               words|            filtered|            features|       rawPrediction|         probability|prediction|predicted_sentiment|
+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+----------+-------------------+
|I love this movie...|[i, love, this, m...|[i, love, this, m...|[0.01370990922053...|[57.0238147530620...|[0.57023814753062...|       0.0|           negative|
|   I hate this movie|[i, hate, this, m...|[i, hate, this, m...|[0.10460961423814...|[63.8305225552969...|[0.63830522555296...|       0.0|           negative|
|The movie was ver...|[the, movie, was,...|[the, movie, was,...|[-0.0372891569776...|[42.2267492494330...|[0.42226749249433...|       1.0|           positive|
+--------------------+--------------------+---

In [ ]:
spark.stop()